{
  "openapi" : "3.1.0",
  "components" : {
    "schemas" : {
      "AbonnementDataSeul" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string",
            "description" : "Identifiant du forfait."
          },
          "volumetrie" : {
            "type" : "string",
            "description" : "Quantité de données mobiles."
          },
          "debit" : {
            "type" : "string",
            "description" : "Débit de connexion."
          },
          "prix" : {
            "type" : "number",
            "format" : "double",
            "description" : "Prix du forfait."
          },
          "url" : {
            "type" : "string",
            "description" : "URL de la page du forfait sur le site officiel."
          },
          "type_forfait" : {
            "type" : "string",
            "description" : "Type de forfait : internet mobile au volume ou internet mobile 4G"
          }
        }
      },
      "Forfait" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string",
            "description" : "Identifiant de la gamme du forfait."
          },
          "desc" : {
            "type" : "string",
            "description" : "Nom de la gamme du forfait."
          },
          "description" : {
            "type" : "string",
            "description" : "Description du forfait."
          },
          "url" : {
            "type" : "string",
            "description" : "URL de la page du forfait sur le site Officiel."
          }
        }
      },
      "ForfaitBloque" : {
        "description" : "Forfait bloqué",
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string",
            "description" : "Identifiant du forfait bloqué."
          },
          "prix" : {
            "type" : "integer",
            "format" : "int32",
            "description" : "Prix du forfait bloqué."
          },
          "credit" : {
            "type" : "integer",
            "format" : "int32",
            "description" : "Montant de crédit du kit."
          },
          "sms_offert" : {
            "type" : "integer",
            "format" : "int32",
            "description" : "Nombre de SMS offert dans le forfait."
          },
          "url" : {
            "type" : "string",
            "description" : "Url de la page du forfait sur le site officiel."
          }
        }
      },
      "ForfaitM" : {
        "description" : "Forfait de la gamme M",
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string",
            "description" : "Identifiant du forfait."
          },
          "volumetrie" : {
            "type" : "string",
            "description" : "Quantité de données mobiles."
          },
          "vocal" : {
            "type" : "string",
            "description" : "Temps d'appel disponible."
          },
          "sms" : {
            "type" : "string",
            "description" : "Nombre de SMS disponibles."
          },
          "prix" : {
            "type" : "number",
            "format" : "double",
            "description" : "Prix du forfait."
          },
          "url" : {
            "type" : "string",
            "description" : "URL de la page du forfait sur le site officiel."
          }
        }
      },
      "KitPrepaye" : {
        "description" : "Forfait prépayé",
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string",
            "description" : "Identifiant du kit prépayé/recharge liberté."
          },
          "credit" : {
            "type" : "integer",
            "format" : "int32",
            "description" : "Montant de crédit du kit/recharge."
          },
          "prix" : {
            "type" : "integer",
            "format" : "int32",
            "description" : "Prix du kit prépayé/recharge liberté."
          },
          "sms_offert" : {
            "type" : "integer",
            "format" : "int32",
            "description" : "Nombre de SMS inclus dans le kit/recharge."
          },
          "duree_validite" : {
            "type" : "integer",
            "format" : "int32",
            "description" : "Durée de validité du kit/recharge (en jours)."
          },
          "url" : {
            "type" : "string",
            "description" : "Url de la page du kit sur le site officiel."
          }
        }
      },
      "TourismCard" : {
        "description" : "Tourism card",
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string",
            "description" : "Identifiant de l'offre tourisme"
          },
          "prix" : {
            "type" : "integer",
            "format" : "int32",
            "description" : "Prix de l'offre tourisme"
          },
          "credit" : {
            "type" : "integer",
            "format" : "int32",
            "description" : "Crédit disponible"
          },
          "volumetrie" : {
            "type" : "string",
            "description" : "Données mobiles disponibles"
          },
          "duree_validite" : {
            "type" : "string",
            "description" : "Durée de validité de l'offre tourisme"
          },
          "url" : {
            "type" : "string",
            "description" : "Url de la page de l'offre tourisme"
          }
        }
      }
    }
  },
  "paths" : {
    "/hello" : {
      "get" : {
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "text/plain" : {
                "schema" : {
                  "type" : "string"
                }
              }
            }
          }
        },
        "summary" : "Hello",
        "tags" : [ "Greeting Resource" ]
      }
    },
    "/offres" : {
      "get" : {
        "tags" : [ "Gammes de Forfaits" ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/Forfait"
                  }
                }
              }
            }
          }
        },
        "summary" : "Get All Offres"
      }
    },
    "/offres/abonnement-data-seul" : {
      "get" : {
        "summary" : "Liste des abonnements de données",
        "description" : "Retourne la liste des abonnements de données (IMV et IM4G).",
        "tags" : [ "Abonnement-data-seul" ],
        "responses" : {
          "200" : {
            "description" : "Liste des abonnements de données (IMV et IM4G)",
            "content" : {
              "application/json" : {
                "examples" : {
                  "Exemple de réponse" : {
                    "value" : [ {
                      "id" : "IMV-10",
                      "volumetrie" : "1 Mo",
                      "debit" : "256 Ko/s",
                      "prix" : 530,
                      "url" : "https://www.opt.nc/sites/serviciel/files/media/file/FI_Internet%20Mobile%20au%20Volume.pdf",
                      "type_forfait" : "IMV"
                    }, {
                      "id" : "IM4G-1",
                      "volumetrie" : "1 Go",
                      "debit" : "150 Mb/s",
                      "prix" : 1908,
                      "url" : "https://www.opt.nc/sites/serviciel/files/media/file/FI_ForfaitInternetMobile4G%202022_1.pdf",
                      "type_forfait" : "IM4G"
                    } ]
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/AbonnementDataSeul"
                }
              }
            }
          }
        }
      }
    },
    "/offres/abonnement-data-seul/im4g" : {
      "get" : {
        "summary" : "Liste des abonnements IM4G",
        "description" : "Retourne la liste des abonnements IM4G.",
        "tags" : [ "Abonnement-data-seul" ],
        "responses" : {
          "200" : {
            "description" : "Liste des abonnements IM4G",
            "content" : {
              "application/json" : {
                "examples" : {
                  "Exemple de réponse" : {
                    "value" : [ {
                      "id" : "IM4G-1",
                      "volumetrie" : "1 Go",
                      "debit" : "150 Mb/s",
                      "prix" : 1908,
                      "url" : "https://www.opt.nc/sites/serviciel/files/media/file/FI_ForfaitInternetMobile4G%202022_1.pdf",
                      "type_forfait" : "IM4G"
                    } ]
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/AbonnementDataSeul"
                }
              }
            }
          }
        }
      }
    },
    "/offres/abonnement-data-seul/imv" : {
      "get" : {
        "summary" : "Liste des abonnements IMV",
        "description" : "Retourne la liste des abonnements IMV.",
        "tags" : [ "Abonnement-data-seul" ],
        "responses" : {
          "200" : {
            "description" : "Liste des abonnements IMV",
            "content" : {
              "application/json" : {
                "examples" : {
                  "Exemple de réponse" : {
                    "value" : [ {
                      "id" : "IMV-10",
                      "volumetrie" : "1 Mo",
                      "debit" : "256 Ko/s",
                      "prix" : 530,
                      "url" : "https://www.opt.nc/sites/serviciel/files/media/file/FI_Internet%20Mobile%20au%20Volume.pdf",
                      "type_forfait" : "IMV"
                    } ]
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/AbonnementDataSeul"
                }
              }
            }
          }
        }
      }
    },
    "/offres/abonnement-data-seul/{id}" : {
      "get" : {
        "summary" : "Détails d'un abonnement spécifique",
        "description" : "Retourne les détails d'un abonnement spécifique de données en fonction de l'ID fourni.",
        "tags" : [ "Abonnement-data-seul" ],
        "parameters" : [ {
          "description" : "ID de l'abonnement",
          "example" : "IMV-10",
          "name" : "id",
          "required" : true,
          "in" : "path",
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Détails de l'abonnement",
            "content" : {
              "application/json" : {
                "examples" : {
                  "Exemple de réponse" : {
                    "value" : {
                      "id" : "IMV-10",
                      "volumetrie" : "1 Mo",
                      "debit" : "256 Ko/s",
                      "prix" : 530,
                      "url" : "https://www.opt.nc/sites/serviciel/files/media/file/FI_Internet%20Mobile%20au%20Volume.pdf",
                      "type_forfait" : "IMV"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/AbonnementDataSeul"
                }
              }
            }
          },
          "404" : {
            "description" : "Abonnement non trouvé"
          }
        }
      }
    },
    "/offres/forfait-bloque" : {
      "get" : {
        "summary" : "Liste des forfaits bloqués",
        "description" : "Retourne la liste complète des forfaits bloqués disponibles.",
        "tags" : [ "Forfaits bloqués" ],
        "responses" : {
          "200" : {
            "description" : "Liste des forfaits bloqués",
            "content" : {
              "application/json" : {
                "examples" : {
                  "Exemple de réponse" : {
                    "value" : [ {
                      "id" : "forfait-bloque-1000",
                      "credit" : 1000,
                      "prix" : 1060,
                      "sms_offert" : 20,
                      "url" : "https://www.opt.nc/particuliers/mobile/quel-forfait-choisir/forfait-bloque-1000"
                    }, {
                      "id" : "forfait-bloque-2000",
                      "credit" : 2000,
                      "prix" : 2120,
                      "sms_offert" : 40,
                      "url" : "https://www.opt.nc/particuliers/mobile/quel-forfait-choisir/forfait-bloque-2000"
                    }, {
                      "id" : "forfait-bloque-3000",
                      "credit" : 3000,
                      "prix" : 3180,
                      "sms_offert" : 60,
                      "url" : "https://www.opt.nc/particuliers/mobile/quel-forfait-choisir/forfait-bloque-3000"
                    }, {
                      "id" : "forfait-bloque-5000",
                      "credit" : 5000,
                      "prix" : 5300,
                      "sms_offert" : 100,
                      "url" : "https://www.opt.nc/particuliers/mobile/quel-forfait-choisir/forfait-bloque-5000"
                    } ]
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ForfaitBloque"
                }
              }
            }
          }
        }
      }
    },
    "/offres/forfait-bloque/{id}" : {
      "get" : {
        "summary" : "Détails d'un forfait bloqué par ID",
        "description" : "Retourne les détails d'un forfait bloqué spécifique en fonction de l'ID fourni.",
        "tags" : [ "Forfaits bloqués" ],
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Détails du forfait bloqué",
            "content" : {
              "application/json" : {
                "examples" : {
                  "Exemple de réponse" : {
                    "value" : {
                      "id" : "forfait-bloque-1000",
                      "credit" : 1000,
                      "prix" : 1060,
                      "sms_offert" : 20,
                      "url" : "https://www.opt.nc/particuliers/mobile/quel-forfait-choisir/forfait-bloque-1000"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ForfaitBloque"
                }
              }
            }
          },
          "404" : {
            "description" : "Forfait bloqué non trouvé"
          }
        }
      }
    },
    "/offres/forfait-m" : {
      "get" : {
        "summary" : "Liste des forfaits de la gamme forfait-m",
        "description" : "Retourne la liste complète des forfaits disponibles dans la gamme forfait-m.",
        "tags" : [ "Forfait-m" ],
        "responses" : {
          "200" : {
            "description" : "Liste des forfaits de la gamme forfait-m",
            "content" : {
              "application/json" : {
                "examples" : {
                  "Exemple de réponse" : {
                    "value" : [ {
                      "id" : "forfait-m-1",
                      "volumetrie" : "1 Go",
                      "vocal" : "1 H",
                      "sms" : "SMS illimités",
                      "prix" : 1000.0,
                      "url" : "https://www.opt.nc/particuliers/mobile/quel-forfait-choisir/forfait-m-1-go"
                    }, {
                      "id" : "forfait-m-100",
                      "volumetrie" : "100 Go",
                      "vocal" : "Appels illimités",
                      "sms" : "SMS illimités",
                      "prix" : 10000.0,
                      "url" : "https://www.opt.nc/particuliers/mobile/quel-forfait-choisir/forfait-m-100-go"
                    } ]
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ForfaitM"
                }
              }
            }
          }
        }
      }
    },
    "/offres/forfait-m/{id}" : {
      "get" : {
        "summary" : "Détails d'un forfait spécifique de la gamme forfait-m",
        "description" : "Retourne les détails d'un forfait spécifique de la gamme forfait-m en fonction de l'ID fourni.",
        "tags" : [ "Forfait-m" ],
        "parameters" : [ {
          "description" : "ID du forfait",
          "example" : "forfait-m-1",
          "name" : "id",
          "required" : true,
          "in" : "path",
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Détails du forfait",
            "content" : {
              "application/json" : {
                "examples" : {
                  "Exemple de réponse" : {
                    "value" : {
                      "id" : "forfait-m-1",
                      "volumetrie" : "1 Go",
                      "vocal" : "1 H",
                      "sms" : "Illimité",
                      "prix" : 1000.0,
                      "url" : "https://www.opt.nc/particuliers/mobile/quel-forfait-choisir/forfait-m-1-go"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ForfaitM"
                }
              }
            }
          },
          "404" : {
            "description" : "Forfait non trouvé"
          }
        }
      }
    },
    "/offres/prepaye" : {
      "get" : {
        "summary" : "Liste des forfaits prépayés",
        "description" : "Retourne la liste complète des forfaits prépayés disponibles.",
        "tags" : [ "Kit Prépayé" ],
        "responses" : {
          "200" : {
            "description" : "Liste des forfaits prépayés",
            "content" : {
              "application/json" : {
                "examples" : {
                  "Exemple de réponse" : {
                    "value" : [ {
                      "id" : "kit-prepaye",
                      "credit" : 3000,
                      "prix" : 6000,
                      "sms_offert" : 0,
                      "duree_validite" : 90,
                      "url" : "https://www.opt.nc/particuliers/mobile/quel-forfait-choisir/kit-prepaye-liberte"
                    }, {
                      "id" : "recharge-liberte-1000",
                      "credit" : 1000,
                      "prix" : 1050,
                      "sms_offert" : 10,
                      "duree_validite" : 120,
                      "url" : "https://www.opt.nc/particuliers/mobile/quel-forfait-choisir/kit-prepaye-liberte"
                    }, {
                      "id" : "recharge-liberte-3000",
                      "credit" : 3000,
                      "prix" : 3150,
                      "sms_offert" : 30,
                      "duree_validite" : 150,
                      "url" : "https://www.opt.nc/particuliers/mobile/quel-forfait-choisir/kit-prepaye-liberte"
                    }, {
                      "id" : "recharge-liberte-5000",
                      "credit" : 5000,
                      "prix" : 5250,
                      "sms_offert" : 50,
                      "duree_validite" : 180,
                      "url" : "https://www.opt.nc/particuliers/mobile/quel-forfait-choisir/kit-prepaye-liberte"
                    } ]
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/KitPrepaye"
                }
              }
            }
          }
        }
      }
    },
    "/offres/prepaye/{id}" : {
      "get" : {
        "summary" : "Détails d'un forfait prépayé par ID",
        "description" : "Retourne les détails d'un forfait prépayé spécifique en fonction de l'ID fourni.",
        "tags" : [ "Kit Prépayé" ],
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Détails du forfait prépayé",
            "content" : {
              "application/json" : {
                "examples" : {
                  "Exemple de réponse" : {
                    "value" : {
                      "id" : "kit-prepaye",
                      "credit" : 3000,
                      "prix" : 6000,
                      "sms_offert" : 0,
                      "duree_validite" : 90,
                      "url" : "https://www.opt.nc/particuliers/mobile/quel-forfait-choisir/kit-prepaye-liberte"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/KitPrepaye"
                }
              }
            }
          },
          "404" : {
            "description" : "Forfait prépayé non trouvé"
          }
        }
      }
    },
    "/offres/tourism-card" : {
      "get" : {
        "summary" : "Liste l'offre de tourisme",
        "tags" : [ "Tourism Card" ],
        "responses" : {
          "200" : {
            "description" : "Détails de la tourism card",
            "content" : {
              "application/json" : {
                "examples" : {
                  "Exemple de réponse" : {
                    "value" : {
                      "id" : "tourism-card",
                      "prix" : "5000",
                      "credit" : "2000",
                      "volumetrie" : "25 Go",
                      "duree_validite" : "3 mois",
                      "url" : "https://www.opt.nc/particuliers/mobile/quel-forfait-choisir/tourism-card-1000"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/TourismCard"
                }
              }
            }
          }
        }
      }
    }
  },
  "tags" : [ {
    "name" : "Abonnement-data-seul",
    "description" : "Accès à un abonnement spécifique"
  }, {
    "name" : "Forfait-m",
    "description" : "Détails d'un forfait spécifique de la gamme forfait-m"
  }, {
    "name" : "Forfaits bloqués",
    "description" : "Accès à un forfait bloqué spécifique par ID"
  }, {
    "name" : "Gammes de Forfaits",
    "description" : "Liste les différentes gammes d'offres télécoms de l'OPT"
  }, {
    "name" : "Kit Prépayé",
    "description" : "Liste de tous les forfaits prépayés"
  }, {
    "name" : "Tourism Card",
    "description" : "Voir les détails de la tourism card"
  } ],
  "info" : {
    "title" : "forfaits-opt-nc API",
    "version" : "1.0.0-SNAPSHOT"
  },
  "servers" : [ {
    "url" : "http://localhost:8080",
    "description" : "Auto generated value"
  }, {
    "url" : "http://0.0.0.0:8080",
    "description" : "Auto generated value"
  } ]
}